### ISSUE TITLE
when I tried to train DA_dehazing, the following errors occurred:

### ISSUE THREAD

**Issue by JuneW00** [HUSTSYJ/DA_dahazing#19]
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    model = create_model(opt)
  File "/home/wuz146/Projects/DA_dahazing/models/__init__.py", line 38, in create_model
    instance.initialize(opt)
  File "/home/wuz146/Projects/DA_dahazing/models/danet_model.py", line 138, in initialize
    self.init_with_pretrained_model('R2S', self.opt.g_r2s_premodel)
  File "/home/wuz146/Projects/DA_dahazing/models/base_model.py", line 142, in init_with_pretrained_model
    net.load_state_dict(state_dict)
  File "/home/wuz146/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator_depth:

**Comment by minhthien2206** [comment]
Did you solve this problem?
