### ISSUE TITLE
output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256],the data of depth only one channel

### ISSUE THREAD

**Issue by 78697187** [HUSTSYJ/DA_dahazing#28]
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/Downloads/yuanguangbin/DA_dahazing/data/aligned_dataset.py", line 116, in __getitem__
    D = self.transform2(D)
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 226, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/user/anaconda3/envs/pyt1/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 284, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

I'm the only one with this problem?

**Comment by chenzhanglu** [comment]
I meet too!do you solve it?
